### ISSUE TITLE
Add IncludeErrorDetail for exposed logs in tests

### ISSUE THREAD

**Issue by ksemkav** [mcctomsk/IntegreSql.EF#1]
Please consider to add `IncludeErrorDetail` and/or `IncludeErrorDetails` into generated connection strings to be able to inspect more logs, when tests with IntegreSQL are failed. 
See [these flags documentation](https://www.npgsql.org/doc/api/Npgsql.NpgsqlConnectionStringBuilder.html#Npgsql_NpgsqlConnectionStringBuilder_IncludeErrorDetail)

Example, why it can be usefull:

![image](https://user-images.githubusercontent.com/12181700/185789163-5e32756a-4d03-42a2-ada9-fbca1a8c9037.png)

https://github.com/mcctomsk/IntegreSql.EF/blob/6dd563bc03063849d15eb07f94bb0b1f0794db60/src/MccSoft.IntegreSql.EF/NpgsqlDatabaseInitializer.cs#L191

**Comment by Shaddix** [comment]
Can you provide a Pull Request for that? :)

**Comment by ksemkav** [comment]
Okay (:
